In [81]:
from __future__ import annotations

import sys
from datetime import datetime
from typing import Optional

import pandas as pd
from cassandra.cluster import Cluster, NoHostAvailable  # pyasyncore 설치로 Python 3.12 호환
from cassandra.policies import DCAwareRoundRobinPolicy
from cassandra.query import SimpleStatement

In [82]:
def load_from_cassandra(
    host: str = "localhost",
    port: int = 9042,
    keyspace: str = "dlim",
    table: str = "ais_class_a_dynamic",
    mmsi_list: Optional[list[str]] = None,
    start_dt: Optional[datetime] = None,
    end_dt: Optional[datetime] = None,
    limit: int = 100_000,
) -> pd.DataFrame:
    """
    Cassandra에서 AIS 데이터를 조회해 pandas DataFrame으로 반환한다.

    Parameters
    ----------
    host       : Cassandra 호스트
    port       : Cassandra 포트
    keyspace   : 키스페이스 이름
    table      : 테이블 이름
    mmsi_list  : 조회할 MMSI 목록 (None이면 전체)
    start_dt   : date_bucket 시작 시각 (포함)
    end_dt     : date_bucket 종료 시각 (포함)
    limit      : 최대 레코드 수

    Returns
    -------
    pd.DataFrame : 조회된 레코드
    """
    print(f"[Cassandra] 연결: {host}:{port} / keyspace={keyspace}")

    try:
        cluster = Cluster(
            contact_points=[host],
            port=port,
            load_balancing_policy=DCAwareRoundRobinPolicy(),
            protocol_version=4,
        )
        session = cluster.connect(keyspace)
    except NoHostAvailable as exc:
        print(f"[오류] Cassandra 연결 실패: {exc}")
        sys.exit(1)
    except Exception as exc:
        print(f"[오류] 예기치 않은 연결 오류: {exc}")
        sys.exit(1)

    COLUMNS = (
        "mmsi, date_bucket, received_at, msg_type, sog, cog, "
        "nav_status, longitude, latitude, rssi, slot_num, snr"
    )

    rows: list[dict] = []

    try:
        if mmsi_list:
            # MMSI 별로 파티션 키 범위 쿼리 → ALLOW FILTERING 불필요
            for mmsi in mmsi_list:
                cql, params = _build_single_mmsi_query(
                    table, COLUMNS, mmsi, start_dt, end_dt, limit
                )
                stmt = SimpleStatement(cql, fetch_size=1000)
                result = session.execute(stmt, params)
                rows.extend(_rows_to_dicts(result))
                if len(rows) >= limit:
                    rows = rows[:limit]
                    break
        else:
            # 전체 조회: date_bucket 범위만 적용 → ALLOW FILTERING 불가피
            cql, params = _build_full_scan_query(
                table, COLUMNS, start_dt, end_dt, limit
            )
            stmt = SimpleStatement(cql, fetch_size=1000)
            result = session.execute(stmt, params)
            rows = _rows_to_dicts(result)
    finally:
        cluster.shutdown()

    if not rows:
        print("[조회] 결과 없음 — 빈 DataFrame 반환")
        return pd.DataFrame(columns=COLUMNS.replace(" ", "").split(","))

    df = pd.DataFrame(rows)

    # datetime 변환 (Cassandra driver는 대부분 datetime으로 반환하나 명시적 보장)
    for col in ("date_bucket", "received_at"):
        if col in df.columns:
            df[col] = pd.to_datetime(df[col], utc=True, errors="coerce")

    print(f"[조회] {table} → {len(df):,}건 로드 완료")
    return df


def _build_single_mmsi_query(
    table: str,
    columns: str,
    mmsi: str,
    start_dt: Optional[datetime],
    end_dt: Optional[datetime],
    limit: int,
) -> tuple[str, list]:
    """단일 MMSI에 대한 파티션 키 쿼리를 생성한다."""
    cql = f"SELECT {columns} FROM {table} WHERE mmsi = %s"
    params: list = [mmsi]

    if start_dt is not None:
        cql += " AND date_bucket >= %s"
        params.append(start_dt)
    if end_dt is not None:
        cql += " AND date_bucket <= %s"
        params.append(end_dt)

    cql += f" LIMIT {limit}"
    return cql, params


def _build_full_scan_query(
    table: str,
    columns: str,
    start_dt: Optional[datetime],
    end_dt: Optional[datetime],
    limit: int,
) -> tuple[str, list]:
    """전체 스캔 쿼리를 생성한다. 날짜 범위가 있으면 ALLOW FILTERING을 추가한다."""
    cql = f"SELECT {columns} FROM {table}"
    params: list = []
    conditions: list[str] = []

    if start_dt is not None:
        conditions.append("date_bucket >= %s")
        params.append(start_dt)
    if end_dt is not None:
        conditions.append("date_bucket <= %s")
        params.append(end_dt)

    if conditions:
        cql += " WHERE " + " AND ".join(conditions) + " ALLOW FILTERING"

    cql += f" LIMIT {limit}"
    return cql, params

def _rows_to_dicts(result) -> list[dict]:
    """cassandra ResultSet을 dict 리스트로 변환한다."""
    return [
        {
            "mmsi":        row.mmsi,
            "date_bucket": row.date_bucket,
            "received_at": row.received_at,
            "msg_type":    row.msg_type,
            "sog":         row.sog,
            "cog":         row.cog,
            "nav_status":  row.nav_status,
            "longitude":   row.longitude,
            "latitude":    row.latitude,
            "rssi":        row.rssi,
            "slot_num":    row.slot_num,
            "snr":         row.snr,
        }
        for row in result
    ]

def split_by_mmsi(df: pd.DataFrame) -> dict[str, pd.DataFrame]:
    """
    전체 DataFrame을 MMSI 단위로 분리한다.

    Parameters
    ----------
    df : load_from_cassandra()가 반환한 DataFrame

    Returns
    -------
    dict[str, pd.DataFrame]
        key   : mmsi 문자열
        value : 해당 선박의 레코드 (date_bucket 오름차순 정렬)
    """
    if df.empty:
        return {}

    mmsi_dfs: dict[str, pd.DataFrame] = {}
    for mmsi, group in df.groupby("mmsi", sort=False):
        mmsi_dfs[str(mmsi)] = (
            group[["date_bucket", "received_at", "msg_type", "sog", "cog", "nav_status", "longitude", "latitude", "rssi", "slot_num", "snr"]]
            .sort_values("date_bucket")
            .reset_index(drop=True)
        )

    return mmsi_dfs

def print_summary(mmsi_dfs: dict[str, pd.DataFrame]) -> None:
    """
    선박별 레코드 수, 관측 시간 등 요약 정보를 콘솔에 출력한다.
    """
    if not mmsi_dfs:
        print("[요약] 데이터 없음")
        return

    total_ships = len(mmsi_dfs)
    total_records = sum(len(v) for v in mmsi_dfs.values())

    print(f"\n[요약] 총 {total_ships:,}척 / {total_records:,}건")

    header = (
        f"  {'MMSI':<14} {'count':>6}   "
        f"{'start_time':<22} {'end_time':<22} {'duration(min)':>13}"
    )
    print(header)
    print("  " + "-" * (len(header) - 2))

    # 레코드 수 내림차순 정렬
    for mmsi, sub_df in sorted(
        mmsi_dfs.items(), key=lambda x: len(x[1]), reverse=True
    ):
        count = len(sub_df)
        start_time = sub_df["date_bucket"].iloc[0]
        end_time = sub_df["date_bucket"].iloc[-1]

        duration_min = (
            (end_time - start_time).total_seconds() / 60.0
            if pd.notna(start_time) and pd.notna(end_time)
            else float("nan")
        )

        # timezone-aware datetime을 보기 좋게 포맷
        fmt = "%Y-%m-%d %H:%M:%S"
        start_str = start_time.strftime(fmt) if pd.notna(start_time) else "N/A"
        end_str = end_time.strftime(fmt) if pd.notna(end_time) else "N/A"

        print(
            f"  {mmsi:<14} {count:>6}   "
            f"{start_str:<22} {end_str:<22} {duration_min:>13.1f}"
        )

In [83]:
# ── 조회 파라미터 ──────────────────────────────────────────────────────────
MMSI_LIST = None          # 특정 선박만: ["538007769", "440100123"]
START_DT  = None          # datetime(2026, 3, 20, 12, 0, 0)
END_DT    = None          # datetime(2026, 3, 20, 13, 0, 0)
LIMIT     = 100_000

# ── 데이터 로드 ────────────────────────────────────────────────────────────
df = load_from_cassandra(
    mmsi_list=MMSI_LIST,
    start_dt=START_DT,
    end_dt=END_DT,
    limit=LIMIT,
)

# ── 선박별 분리 ────────────────────────────────────────────────────────────
mmsi_dfs = split_by_mmsi(df)
print_summary(mmsi_dfs)
print(df)

[Cassandra] 연결: localhost:9042 / keyspace=dlim
[조회] ais_class_a_dynamic → 58,167건 로드 완료

[요약] 총 157척 / 58,167건
  MMSI            count   start_time             end_time               duration(min)
  -----------------------------------------------------------------------------------
  440016000        1803   2026-03-20 11:59:24    2026-03-20 12:59:28             60.1
  636021910        1802   2026-03-20 11:59:24    2026-03-20 12:59:28             60.1
  256459000        1795   2026-03-20 11:59:23    2026-03-20 12:59:29             60.1
  413703960        1783   2026-03-20 11:59:23    2026-03-20 12:59:29             60.1
  538007769        1773   2026-03-20 11:59:23    2026-03-20 12:59:29             60.1
  636015991        1747   2026-03-20 11:59:23    2026-03-20 12:59:29             60.1
  668116244        1056   2026-03-23 14:59:25    2026-03-23 15:34:35             35.2
  273428130        1053   2026-03-23 14:59:26    2026-03-23 15:34:36             35.2
  636016053        1051   2026-03-23 14:59:26    2026-03-23 15:34:36             35.2
  414061000        1050   2026-03-23 14:59:25    2026-03-23 15:34:35             35.2
  564853000        1050   2026-03-23 14:59:27    2026-03-23 15:34:35             35.1
  246302000        1048   2026-03-23 14:59:26    2026-03-23 15:34:36             35.2
  273841100        1046   2026-03-23 14:59:25    2026-03-23 15:34:35             35.2
  352986195         602   2026-03-20 11:59:24    2026-03-20 12:59:30             60.1
  355216000         602   2026-03-20 11:59:23    2026-03-20 12:59:29             60.1
  255806059         601   2026-03-20 11:59:28    2026-03-20 12:59:28             60.0
  511101063         601   2026-03-20 11:59:27    2026-03-20 12:59:27             60.0
  440310510         587   2026-03-25 11:02:06    2026-03-25 11:21:38             19.5
  356758000         587   2026-03-25 11:02:04    2026-03-25 11:21:38             19.6
  636020892         587   2026-03-25 11:02:03    2026-03-25 11:21:37             19.6
  312716000         586   2026-03-25 11:02:07    2026-03-25 11:21:39             19.5
  352927000         584   2026-03-25 11:02:08    2026-03-25 11:21:38             19.5
  440000340         584   2026-03-25 11:02:06    2026-03-25 11:21:38             19.5
  636023189         578   2026-03-25 11:02:24    2026-03-25 11:21:38             19.2
  416044000         577   2026-03-25 11:02:27    2026-03-25 11:21:39             19.2
  563147100         575   2026-03-25 11:02:29    2026-03-25 11:21:37             19.1
  219710000         575   2026-03-25 11:02:29    2026-03-25 11:21:37             19.1
  636022201         552   2026-03-25 11:02:30    2026-03-25 11:21:38             19.1
  453936486         492   2026-03-20 11:59:23    2026-03-20 12:59:26             60.1
  988864582         492   2026-03-20 11:59:24    2026-03-20 12:59:26             60.0
  225126564         491   2026-03-20 11:59:24    2026-03-20 12:59:29             60.1
  140314169         491   2026-03-20 11:59:24    2026-03-20 12:59:30             60.1
  580762616         490   2026-03-20 11:59:27    2026-03-20 12:59:24             60.0
  622576417         490   2026-03-20 11:59:27    2026-03-20 12:59:27             60.0
  423636631         489   2026-03-20 11:59:24    2026-03-20 12:59:24             60.0
  254264412         488   2026-03-20 11:59:23    2026-03-20 12:59:27             60.1
  395493027         488   2026-03-20 11:59:26    2026-03-20 12:59:27             60.0
  158631920         488   2026-03-20 11:59:23    2026-03-20 12:59:28             60.1
  182950005         488   2026-03-20 11:59:23    2026-03-20 12:59:26             60.1
  725186041         488   2026-03-20 11:59:24    2026-03-20 12:59:24             60.0
  903811553         488   2026-03-20 11:59:26    2026-03-20 12:59:27             60.0
  156106498         487   2026-03-20 11:59:26    2026-03-20 12:59:26             60.0
  339972718         487   2026-03-20 11:59:26    2026-03-20 12:59:30             60.1
  157419116         485   2026-03-20 11:59:25    2026-03-20 12:59:24             60.0
  212037228         485   2026-03-20 11:59:23    2026-03-20 12:59:22             60.0
  457947874         485   2026-03-20 11:59:27    2026-03-20 12:59:27             60.0
  211769104         484   2026-03-20 11:59:24    2026-03-20 12:59:28             60.1
  648159944         483   2026-03-20 11:59:24    2026-03-20 12:59:28             60.1
  273338020         361   2026-03-20 11:59:25    2026-03-20 12:59:25             60.0
  352986187         361   2026-03-20 11:59:24    2026-03-20 12:59:24             60.0
  357843000         361   2026-03-20 11:59:26    2026-03-20 12:59:26             60.0
  538006129         361   2026-03-20 11:59:28    2026-03-20 12:59:28             60.0
  356131000         361   2026-03-20 11:59:25    2026-03-20 12:59:25             60.0
  353241000         361   2026-03-20 11:59:29    2026-03-20 12:59:29             60.0
  205749000         361   2026-03-20 11:59:23    2026-03-20 12:59:23             60.0
  273356070         361   2026-03-20 11:59:25    2026-03-20 12:59:25             60.0
  419766000         360   2026-03-20 11:59:31    2026-03-20 12:59:21             59.8
  273219590         360   2026-03-20 11:59:32    2026-03-20 12:59:22             59.8
  564538000         360   2026-03-20 11:59:30    2026-03-20 12:59:20             59.8
  574003640         352   2026-03-23 14:59:28    2026-03-23 15:34:34             35.1
  352003948         352   2026-03-23 14:59:29    2026-03-23 15:34:35             35.1
  440413000         352   2026-03-23 14:59:27    2026-03-23 15:34:33             35.1
  564957000         352   2026-03-23 14:59:29    2026-03-23 15:34:35             35.1
  636022279         352   2026-03-23 14:59:26    2026-03-23 15:34:32             35.1
  440006970         352   2026-03-23 14:59:25    2026-03-23 15:34:31             35.1
  538007429         352   2026-03-23 14:59:27    2026-03-23 15:34:33             35.1
  403547000         352   2026-03-23 14:59:30    2026-03-23 15:34:36             35.1
  477591600         352   2026-03-23 14:59:26    2026-03-23 15:34:32             35.1
  413212060         352   2026-03-23 14:59:27    2026-03-23 15:34:33             35.1
  636014571         352   2026-03-23 14:59:30    2026-03-23 15:34:36             35.1
  354736000         352   2026-03-23 14:59:25    2026-03-23 15:34:31             35.1
  248496000         352   2026-03-23 14:59:28    2026-03-23 15:34:34             35.1
  538009351         352   2026-03-23 14:59:27    2026-03-23 15:34:33             35.1
  477714600         352   2026-03-23 14:59:26    2026-03-23 15:34:32             35.1
  855215235         302   2026-03-20 11:59:29    2026-03-20 12:59:29             60.0
  128864111         301   2026-03-20 11:59:29    2026-03-20 12:59:29             60.0
  357631084         301   2026-03-20 11:59:28    2026-03-20 12:59:28             60.0
  687752125         300   2026-03-20 11:59:25    2026-03-20 12:59:26             60.0
  418282702         300   2026-03-20 11:59:28    2026-03-20 12:59:28             60.0
  602283236         300   2026-03-20 11:59:27    2026-03-20 12:59:28             60.0
  701685138         300   2026-03-20 11:59:22    2026-03-20 12:59:23             60.0
  964638703         300   2026-03-20 11:59:26    2026-03-20 12:59:26             60.0
  195006888         300   2026-03-20 11:59:27    2026-03-20 12:59:27             60.0
  836136505         295   2026-03-20 11:59:31    2026-03-20 12:59:29             60.0
  808843953         295   2026-03-20 11:59:24    2026-03-20 12:59:25             60.0
  341689917         294   2026-03-20 11:59:29    2026-03-20 12:59:23             59.9
  576289351         293   2026-03-20 11:59:29    2026-03-20 12:59:25             59.9
  509987432         293   2026-03-20 11:59:23    2026-03-20 12:59:25             60.0
  361293625         292   2026-03-20 11:59:28    2026-03-20 12:59:27             60.0
  760702198         292   2026-03-20 11:59:24    2026-03-20 12:59:24             60.0
  232697378         292   2026-03-20 11:59:23    2026-03-20 12:59:26             60.1
  697354089         292   2026-03-20 11:59:32    2026-03-20 12:59:26             59.9
  738514668         291   2026-03-20 11:59:31    2026-03-20 12:59:24             59.9
  348140341         290   2026-03-20 11:59:29    2026-03-20 12:59:24             59.9
  477283000         212   2026-03-23 14:59:25    2026-03-23 15:34:35             35.2
  538009273         212   2026-03-23 14:59:26    2026-03-23 15:34:36             35.2
  636024421         211   2026-03-23 14:59:31    2026-03-23 15:34:31             35.0
  538009886         211   2026-03-23 14:59:30    2026-03-23 15:34:30             35.0
  636015714         211   2026-03-23 14:59:29    2026-03-23 15:34:29             35.0
  477942100         211   2026-03-23 14:59:30    2026-03-23 15:34:30             35.0
  538004987         211   2026-03-23 14:59:29    2026-03-23 15:34:29             35.0
  636023252         211   2026-03-23 14:59:29    2026-03-23 15:34:29             35.0
  440658000         211   2026-03-23 14:59:33    2026-03-23 15:34:33             35.0
  215573000         211   2026-03-23 14:59:29    2026-03-23 15:34:29             35.0
  367080000         211   2026-03-23 14:59:33    2026-03-23 15:34:33             35.0
  636018314         211   2026-03-23 14:59:34    2026-03-23 15:34:34             35.0
  241632000         211   2026-03-23 14:59:29    2026-03-23 15:34:29             35.0
  477476300         196   2026-03-25 11:02:07    2026-03-25 11:21:37             19.5
  311054300         196   2026-03-25 11:02:05    2026-03-25 11:21:35             19.5
  440363000         196   2026-03-25 11:02:06    2026-03-25 11:21:36             19.5
  563162500         196   2026-03-25 11:02:06    2026-03-25 11:21:36             19.5
  636020590         196   2026-03-25 11:02:05    2026-03-25 11:21:35             19.5
  352002591         196   2026-03-25 11:02:09    2026-03-25 11:21:39             19.5
  352004507         196   2026-03-25 11:02:09    2026-03-25 11:21:39             19.5
  538006103         193   2026-03-25 11:02:26    2026-03-25 11:21:38             19.2
  219357000         193   2026-03-25 11:02:23    2026-03-25 11:21:35             19.2
  563021700         192   2026-03-25 11:02:27    2026-03-25 11:21:33             19.1
  273415260         192   2026-03-25 11:02:29    2026-03-25 11:21:35             19.1
  353282000         192   2026-03-25 11:02:32    2026-03-25 11:21:38             19.1
  636020552         191   2026-03-25 11:02:35    2026-03-25 11:21:35             19.0
  538002641         118   2026-03-25 11:02:06    2026-03-25 11:21:36             19.5
  477947700         118   2026-03-25 11:02:05    2026-03-25 11:21:35             19.5
  563172200         118   2026-03-25 11:02:07    2026-03-25 11:21:37             19.5
  440021790         116   2026-03-25 11:02:23    2026-03-25 11:21:33             19.2
  477634100         116   2026-03-25 11:02:25    2026-03-25 11:21:35             19.2
  511100779         116   2026-03-25 11:02:28    2026-03-25 11:21:38             19.2
  636022717          20   2026-03-20 12:00:19    2026-03-20 12:57:19             57.0
  413384150          20   2026-03-20 12:00:14    2026-03-20 12:57:14             57.0
  440516000          20   2026-03-20 12:00:17    2026-03-20 12:57:17             57.0
  440629000          20   2026-03-20 12:00:13    2026-03-20 12:57:13             57.0
  636019900          20   2026-03-20 12:00:10    2026-03-20 12:57:10             57.0
  209605000          20   2026-03-20 12:00:23    2026-03-20 12:57:23             57.0
  528659074          18   2026-03-20 12:00:45    2026-03-20 12:57:45             57.0
  914070447          18   2026-03-20 12:00:43    2026-03-20 12:57:43             57.0
  527340686          18   2026-03-20 12:00:42    2026-03-20 12:57:42             57.0
  521017178          18   2026-03-20 12:00:46    2026-03-20 12:57:46             57.0
  685123255          18   2026-03-20 12:00:41    2026-03-20 12:57:41             57.0
  390412225          18   2026-03-20 12:00:47    2026-03-20 12:57:47             57.0
  327919552          18   2026-03-20 12:00:41    2026-03-20 12:57:41             57.0
  111131433          18   2026-03-20 12:00:44    2026-03-20 12:57:44             57.0
  221376372          18   2026-03-20 12:00:42    2026-03-20 12:57:42             57.0
  386008049          18   2026-03-20 12:00:47    2026-03-20 12:57:47             57.0
  440250000          12   2026-03-23 15:00:37    2026-03-23 15:33:37             33.0
  219029326          12   2026-03-23 15:00:49    2026-03-23 15:33:49             33.0
  352004689          12   2026-03-23 15:00:17    2026-03-23 15:33:17             33.0
  370894000          12   2026-03-23 15:00:25    2026-03-23 15:33:25             33.0
  219031000          12   2026-03-23 15:00:31    2026-03-23 15:33:31             33.0
  440343000           7   2026-03-25 11:02:12    2026-03-25 11:20:12             18.0
  220059000           7   2026-03-25 11:02:02    2026-03-25 11:20:02             18.0
  538005269           7   2026-03-25 11:02:06    2026-03-25 11:20:06             18.0
  566785000           7   2026-03-25 11:02:11    2026-03-25 11:20:11             18.0
  352001515           7   2026-03-25 11:02:04    2026-03-25 11:20:04             18.0
  370216000           7   2026-03-25 11:02:27    2026-03-25 11:20:27             18.0
  238293000           7   2026-03-25 11:02:10    2026-03-25 11:20:10             18.0
  563526000           7   2026-03-25 11:02:06    2026-03-25 11:20:06             18.0
  563122800           7   2026-03-25 11:02:21    2026-03-25 11:20:21             18.0
  563141200           7   2026-03-25 11:02:02    2026-03-25 11:20:02             18.0
            mmsi                      date_bucket  \
0      273841100 2026-03-23 15:06:21.639000+00:00
1      574003640 2026-03-23 15:30:28.096000+00:00
2      255806059 2026-03-20 12:25:40.379000+00:00
3      352986195 2026-03-20 12:38:48.017000+00:00
4      687752125 2026-03-20 12:56:16.054000+00:00
...          ...                              ...
58162  538007769 2026-03-20 12:14:25.487000+00:00
58163  413703960 2026-03-20 12:19:55.578000+00:00
58164  538009351 2026-03-23 15:15:15.129000+00:00
58165  477947700 2026-03-25 11:12:25.030000+00:00
58166  273338020 2026-03-20 12:59:05.804000+00:00

                           received_at  msg_type    sog     cog  nav_status  \
0     2026-03-23 16:02:04.206000+00:00         1  278.0  3074.0        14.0
1     2026-03-23 16:04:50.359000+00:00         1  166.0   500.0        12.0
2     2026-03-20 17:47:05.889000+00:00         1  149.0  2132.0         1.0
3     2026-03-20 17:48:57.649000+00:00         1  197.0  1775.0        10.0
4     2026-03-20 17:51:19.946000+00:00         1  111.0  1213.0         NaN
...                                ...       ...    ...     ...         ...
58162 2026-03-20 17:45:24.090000+00:00         1  274.0  1969.0         6.0
58163 2026-03-20 17:46:15.862000+00:00         1  232.0  2674.0         6.0
58164 2026-03-23 16:03:05.536000+00:00         1  180.0  1204.0         6.0
58165 2026-03-25 11:44:13.343000+00:00         1   20.0  2055.0         2.0
58166 2026-03-20 17:51:46.881000+00:00         1   26.0  2898.0         8.0

        longitude   latitude        rssi  slot_num         snr
0      129.368460  35.149060    8.800000       812 -110.800003
1      129.144710  35.131650   21.299999      1034  -98.699997
2      129.271380  34.965530   13.600000      1492 -107.400002
3      128.790130  34.959220    7.200000      1788 -111.800003
4      129.453975  36.191567  -65.900002      1779   11.300000
...           ...        ...         ...       ...         ...
58162  129.054610  35.063460   32.700001       949  -86.900002
58163  129.446120  34.952260    6.200000      2083 -112.599998
58164  129.165180  35.052890   22.400000       547  -97.800003
58165  128.805480  34.871750 -107.500000       925   12.800000
58166  129.065750  34.914170   15.300000       183 -105.300003

[58167 rows x 12 columns]

In [84]:
df["mmsi"].sort_values().drop_duplicates()

49186    111131433
19821    128864111
4710     140314169
51411    156106498
32227    157419116
           ...
24931    855215235
11346    903811553
47347    914070447
21871    964638703
34666    988864582
Name: mmsi, Length: 157, dtype: str

In [92]:
import datetime

df_mar23 = df[df["date_bucket"].dt.date == datetime.date(2026, 3, 25)].copy()

#df_sort = df.sort_values(["mmsi","date_bucket"])

df_sort = df_mar23.sort_values(["date_bucket"])

In [93]:
with pd.option_context("display.max_rows", None):
    display(df_sort[["mmsi","date_bucket","slot_num"]])

            mmsi                      date_bucket  slot_num
16768  220059000 2026-03-25 11:02:02.758000+00:00       114
52883  563141200 2026-03-25 11:02:02.866000+00:00       113
42885  636020892 2026-03-25 11:02:03.853000+00:00       160
31343  356758000 2026-03-25 11:02:04.777000+00:00       193
7485   352001515 2026-03-25 11:02:04.936000+00:00       199
10490  477947700 2026-03-25 11:02:05.026000+00:00       213
22663  311054300 2026-03-25 11:02:05.142000+00:00       201
22520  636020892 2026-03-25 11:02:05.865000+00:00       228
32116  636020590 2026-03-25 11:02:05.971000+00:00       233
33921  538005269 2026-03-25 11:02:06.343000+00:00       240
4409   563526000 2026-03-25 11:02:06.347000+00:00       254
14798  440310510 2026-03-25 11:02:06.370000+00:00       257
39755  440363000 2026-03-25 11:02:06.462000+00:00       250
5610   440000340 2026-03-25 11:02:06.524000+00:00       255
17297  538002641 2026-03-25 11:02:06.534000+00:00       265
53320  563162500 2026-03-25 11:02:06.667000+00:00       279
27626  356758000 2026-03-25 11:02:06.777000+00:00       261
26750  312716000 2026-03-25 11:02:07.146000+00:00       274
851    477476300 2026-03-25 11:02:07.462000+00:00       283
4858   563172200 2026-03-25 11:02:07.711000+00:00       310
19793  636020892 2026-03-25 11:02:07.852000+00:00       303
5007   440310510 2026-03-25 11:02:08.370000+00:00       325
56378  440000340 2026-03-25 11:02:08.523000+00:00       323
56001  352927000 2026-03-25 11:02:08.705000+00:00       334
31236  356758000 2026-03-25 11:02:08.777000+00:00       336
15327  312716000 2026-03-25 11:02:09.147000+00:00       342
24086  352004507 2026-03-25 11:02:09.174000+00:00       368
28209  352002591 2026-03-25 11:02:09.493000+00:00       365
11257  636020892 2026-03-25 11:02:09.861000+00:00       378
6862   238293000 2026-03-25 11:02:10.162000+00:00       404
31863  440310510 2026-03-25 11:02:10.371000+00:00       400
19530  440000340 2026-03-25 11:02:10.523000+00:00       398
13172  352927000 2026-03-25 11:02:10.703000+00:00       402
37028  356758000 2026-03-25 11:02:10.777000+00:00       411
41797  311054300 2026-03-25 11:02:11.141000+00:00       404
23347  312716000 2026-03-25 11:02:11.146000+00:00       417
56349  566785000 2026-03-25 11:02:11.809000+00:00       455
33608  636020892 2026-03-25 11:02:11.853000+00:00       453
30241  636020590 2026-03-25 11:02:11.970000+00:00       436
22985  440343000 2026-03-25 11:02:12.144000+00:00       489
41280  440310510 2026-03-25 11:02:12.372000+00:00       475
53743  440363000 2026-03-25 11:02:12.450000+00:00       453
43231  440000340 2026-03-25 11:02:12.524000+00:00       473
14096  563162500 2026-03-25 11:02:12.668000+00:00       482
37881  352927000 2026-03-25 11:02:12.704000+00:00       477
45589  356758000 2026-03-25 11:02:12.776000+00:00       486
7718   312716000 2026-03-25 11:02:13.146000+00:00       492
51211  477476300 2026-03-25 11:02:13.463000+00:00       486
11203  636020892 2026-03-25 11:02:13.854000+00:00       528
9586   440310510 2026-03-25 11:02:14.370000+00:00       550
27560  440000340 2026-03-25 11:02:14.524000+00:00       548
9397   352927000 2026-03-25 11:02:14.703000+00:00       552
35216  356758000 2026-03-25 11:02:14.777000+00:00       561
9150   477947700 2026-03-25 11:02:15.026000+00:00       551
43978  312716000 2026-03-25 11:02:15.147000+00:00       567
39292  352004507 2026-03-25 11:02:15.173000+00:00       571
28890  352002591 2026-03-25 11:02:15.493000+00:00       568
28378  636020892 2026-03-25 11:02:15.852000+00:00       603
13868  440310510 2026-03-25 11:02:16.370000+00:00       625
52189  440000340 2026-03-25 11:02:16.525000+00:00       623
2944   538002641 2026-03-25 11:02:16.534000+00:00       603
2869   352927000 2026-03-25 11:02:16.704000+00:00       627
24828  356758000 2026-03-25 11:02:16.777000+00:00       636
33255  311054300 2026-03-25 11:02:17.141000+00:00       629
36270  312716000 2026-03-25 11:02:17.147000+00:00       642
28216  563172200 2026-03-25 11:02:17.710000+00:00       648
10923  636020892 2026-03-25 11:02:17.853000+00:00       678
34867  636020590 2026-03-25 11:02:17.970000+00:00       661
33237  440310510 2026-03-25 11:02:18.369000+00:00       700
5845   440363000 2026-03-25 11:02:18.451000+00:00       678
55876  440000340 2026-03-25 11:02:18.523000+00:00       698
44719  563162500 2026-03-25 11:02:18.668000+00:00       707
32489  352927000 2026-03-25 11:02:18.705000+00:00       702
30622  356758000 2026-03-25 11:02:18.776000+00:00       711
32496  312716000 2026-03-25 11:02:19.146000+00:00       717
26808  477476300 2026-03-25 11:02:19.461000+00:00       711
2668   636020892 2026-03-25 11:02:19.853000+00:00       753
13951  440310510 2026-03-25 11:02:20.369000+00:00       775
41050  440000340 2026-03-25 11:02:20.524000+00:00       773
33966  352927000 2026-03-25 11:02:20.703000+00:00       777
4272   356758000 2026-03-25 11:02:20.777000+00:00       786
15717  312716000 2026-03-25 11:02:21.147000+00:00       792
41570  352004507 2026-03-25 11:02:21.174000+00:00       796
42305  563122800 2026-03-25 11:02:21.237000+00:00       798
13398  352002591 2026-03-25 11:02:21.492000+00:00       793
54477  636020892 2026-03-25 11:02:21.853000+00:00       828
958    440310510 2026-03-25 11:02:22.371000+00:00       850
53122  440000340 2026-03-25 11:02:22.523000+00:00       848
4875   352927000 2026-03-25 11:02:22.715000+00:00       852
32794  356758000 2026-03-25 11:02:22.776000+00:00       861
2041   311054300 2026-03-25 11:02:23.141000+00:00       854
41113  312716000 2026-03-25 11:02:23.146000+00:00       867
15504  440021790 2026-03-25 11:02:23.168000+00:00       888
4705   219357000 2026-03-25 11:02:23.400000+00:00       878
41215  636020892 2026-03-25 11:02:23.853000+00:00       903
16002  636020590 2026-03-25 11:02:23.969000+00:00       886
9979   636023189 2026-03-25 11:02:24.252000+00:00       917
48441  440310510 2026-03-25 11:02:24.369000+00:00       925
54565  440363000 2026-03-25 11:02:24.451000+00:00       903
56152  440000340 2026-03-25 11:02:24.523000+00:00       923
43278  563162500 2026-03-25 11:02:24.667000+00:00       932
3169   352927000 2026-03-25 11:02:24.704000+00:00       927
19078  356758000 2026-03-25 11:02:24.776000+00:00       936
29719  477947700 2026-03-25 11:02:25.025000+00:00       926
12151  312716000 2026-03-25 11:02:25.146000+00:00       942
36751  477634100 2026-03-25 11:02:25.461000+00:00       967
8926   477476300 2026-03-25 11:02:25.462000+00:00       936
49709  636020892 2026-03-25 11:02:25.854000+00:00       978
17266  636023189 2026-03-25 11:02:26.252000+00:00       985
15665  440310510 2026-03-25 11:02:26.370000+00:00      1000
6930   440000340 2026-03-25 11:02:26.523000+00:00       998
29864  538002641 2026-03-25 11:02:26.536000+00:00       978
13552  352927000 2026-03-25 11:02:26.704000+00:00      1002
35122  356758000 2026-03-25 11:02:26.776000+00:00      1011
24940  538006103 2026-03-25 11:02:26.938000+00:00      1014
29091  312716000 2026-03-25 11:02:27.146000+00:00      1017
43694  352004507 2026-03-25 11:02:27.174000+00:00      1021
25197  370216000 2026-03-25 11:02:27.428000+00:00      1036
2764   416044000 2026-03-25 11:02:27.454000+00:00      1031
3817   352002591 2026-03-25 11:02:27.492000+00:00      1018
14140  563172200 2026-03-25 11:02:27.711000+00:00      1023
10040  636020892 2026-03-25 11:02:27.853000+00:00      1053
20777  563021700 2026-03-25 11:02:27.989000+00:00      1080
8651   636023189 2026-03-25 11:02:28.253000+00:00      1060
37545  440310510 2026-03-25 11:02:28.370000+00:00      1075
41032  511100779 2026-03-25 11:02:28.485000+00:00      1093
32969  440000340 2026-03-25 11:02:28.524000+00:00      1073
3154   352927000 2026-03-25 11:02:28.703000+00:00      1077
50440  356758000 2026-03-25 11:02:28.776000+00:00      1086
21619  311054300 2026-03-25 11:02:29.141000+00:00      1079
46025  312716000 2026-03-25 11:02:29.147000+00:00      1092
34591  273415260 2026-03-25 11:02:29.210000+00:00      1121
30784  219357000 2026-03-25 11:02:29.399000+00:00      1081
35213  416044000 2026-03-25 11:02:29.454000+00:00      1099
15848  636020892 2026-03-25 11:02:29.853000+00:00      1128
19293  563147100 2026-03-25 11:02:29.880000+00:00      1131
11194  219710000 2026-03-25 11:02:29.964000+00:00      1144
55457  636020590 2026-03-25 11:02:29.969000+00:00      1111
45516  636023189 2026-03-25 11:02:30.253000+00:00      1135
48246  440310510 2026-03-25 11:02:30.369000+00:00      1150
11727  440363000 2026-03-25 11:02:30.450000+00:00      1128
22906  440000340 2026-03-25 11:02:30.524000+00:00      1148
35552  636022201 2026-03-25 11:02:30.574000+00:00      1172
3430   563162500 2026-03-25 11:02:30.666000+00:00      1157
35547  352927000 2026-03-25 11:02:30.704000+00:00      1152
4075   356758000 2026-03-25 11:02:30.775000+00:00      1161
57257  312716000 2026-03-25 11:02:31.147000+00:00      1167
54589  416044000 2026-03-25 11:02:31.453000+00:00      1174
48292  477476300 2026-03-25 11:02:31.461000+00:00      1161
15221  636020892 2026-03-25 11:02:31.852000+00:00      1203
44005  563147100 2026-03-25 11:02:31.880000+00:00      1199
49809  219710000 2026-03-25 11:02:31.962000+00:00      1212
43147  636023189 2026-03-25 11:02:32.253000+00:00      1210
25489  353282000 2026-03-25 11:02:32.311000+00:00      1218
3962   440310510 2026-03-25 11:02:32.370000+00:00      1225
48587  440000340 2026-03-25 11:02:32.523000+00:00      1223
15814  636022201 2026-03-25 11:02:32.574000+00:00      1240
32528  352927000 2026-03-25 11:02:32.704000+00:00      1227
45005  356758000 2026-03-25 11:02:32.776000+00:00      1236
29325  538006103 2026-03-25 11:02:32.937000+00:00      1217
33824  312716000 2026-03-25 11:02:33.146000+00:00      1242
46188  440021790 2026-03-25 11:02:33.168000+00:00      1226
38392  352004507 2026-03-25 11:02:33.173000+00:00      1246
50254  416044000 2026-03-25 11:02:33.454000+00:00      1249
4516   352002591 2026-03-25 11:02:33.492000+00:00      1243
52492  636020892 2026-03-25 11:02:33.853000+00:00      1278
55451  563147100 2026-03-25 11:02:33.880000+00:00      1274
50257  219710000 2026-03-25 11:02:33.963000+00:00      1287
12523  563021700 2026-03-25 11:02:33.989000+00:00      1283
38087  636023189 2026-03-25 11:02:34.252000+00:00      1285
6860   440310510 2026-03-25 11:02:34.373000+00:00      1300
44108  440000340 2026-03-25 11:02:34.524000+00:00      1298
10174  636022201 2026-03-25 11:02:34.574000+00:00      1315
37597  352927000 2026-03-25 11:02:34.704000+00:00      1302
46137  356758000 2026-03-25 11:02:34.777000+00:00      1311
10593  477947700 2026-03-25 11:02:35.025000+00:00      1301
7603   311054300 2026-03-25 11:02:35.141000+00:00      1304
22035  312716000 2026-03-25 11:02:35.146000+00:00      1317
6404   273415260 2026-03-25 11:02:35.210000+00:00      1324
43399  219357000 2026-03-25 11:02:35.401000+00:00      1306
52765  416044000 2026-03-25 11:02:35.454000+00:00      1324
27288  477634100 2026-03-25 11:02:35.461000+00:00      1305
15869  636020552 2026-03-25 11:02:35.462000+00:00      1342
27906  636020892 2026-03-25 11:02:35.859000+00:00      1353
35201  563147100 2026-03-25 11:02:35.891000+00:00      1349
12161  219710000 2026-03-25 11:02:35.961000+00:00      1362
11568  636020590 2026-03-25 11:02:35.969000+00:00      1336
38545  636023189 2026-03-25 11:02:36.253000+00:00      1360
46927  440310510 2026-03-25 11:02:36.371000+00:00      1375
5618   440363000 2026-03-25 11:02:36.464000+00:00      1353
4139   440000340 2026-03-25 11:02:36.528000+00:00      1373
36991  538002641 2026-03-25 11:02:36.543000+00:00      1353
32286  636022201 2026-03-25 11:02:36.575000+00:00      1390
14469  563162500 2026-03-25 11:02:36.667000+00:00      1382
4975   352927000 2026-03-25 11:02:36.714000+00:00      1377
12555  356758000 2026-03-25 11:02:36.777000+00:00      1386
5709   312716000 2026-03-25 11:02:37.153000+00:00      1392
57982  416044000 2026-03-25 11:02:37.465000+00:00      1399
2882   477476300 2026-03-25 11:02:37.466000+00:00      1386
17784  563172200 2026-03-25 11:02:37.713000+00:00      1398
10597  636020892 2026-03-25 11:02:37.853000+00:00      1428
11662  563147100 2026-03-25 11:02:37.886000+00:00      1424
19614  219710000 2026-03-25 11:02:37.965000+00:00      1437
27278  636023189 2026-03-25 11:02:38.260000+00:00      1435
26548  353282000 2026-03-25 11:02:38.323000+00:00      1421
5899   440310510 2026-03-25 11:02:38.384000+00:00      1450
58102  511100779 2026-03-25 11:02:38.493000+00:00      1431
9271   440000340 2026-03-25 11:02:38.524000+00:00      1448
5038   636022201 2026-03-25 11:02:38.587000+00:00      1465
30677  352927000 2026-03-25 11:02:38.713000+00:00      1452
48973  356758000 2026-03-25 11:02:38.790000+00:00      1461
54505  538006103 2026-03-25 11:02:38.944000+00:00      1442
49276  312716000 2026-03-25 11:02:39.146000+00:00      1467
11929  352004507 2026-03-25 11:02:39.178000+00:00      1471
56521  416044000 2026-03-25 11:02:39.464000+00:00      1474
46490  352002591 2026-03-25 11:02:39.495000+00:00      1468
25721  636020892 2026-03-25 11:02:39.854000+00:00      1503
63     563147100 2026-03-25 11:02:39.885000+00:00      1499
56162  219710000 2026-03-25 11:02:39.977000+00:00      1512
43977  563021700 2026-03-25 11:02:39.993000+00:00      1508
20814  636023189 2026-03-25 11:02:40.258000+00:00      1510
34530  440310510 2026-03-25 11:02:40.384000+00:00      1525
48538  440000340 2026-03-25 11:02:40.525000+00:00      1523
50008  636022201 2026-03-25 11:02:40.587000+00:00      1540
12131  352927000 2026-03-25 11:02:40.712000+00:00      1527
2047   356758000 2026-03-25 11:02:40.791000+00:00      1536
8470   312716000 2026-03-25 11:02:41.148000+00:00      1542
38380  311054300 2026-03-25 11:02:41.149000+00:00      1529
34661  273415260 2026-03-25 11:02:41.210000+00:00      1549
29266  219357000 2026-03-25 11:02:41.412000+00:00      1531
25468  416044000 2026-03-25 11:02:41.459000+00:00      1549
45718  636020552 2026-03-25 11:02:41.459000+00:00      1545
742    636020892 2026-03-25 11:02:41.862000+00:00      1578
2541   563147100 2026-03-25 11:02:41.894000+00:00      1574
53434  219710000 2026-03-25 11:02:41.971000+00:00      1587
17007  636020590 2026-03-25 11:02:41.971000+00:00      1561
37555  636023189 2026-03-25 11:02:42.266000+00:00      1585
11030  440310510 2026-03-25 11:02:42.374000+00:00      1600
24615  440363000 2026-03-25 11:02:42.452000+00:00      1578
42651  440000340 2026-03-25 11:02:42.532000+00:00      1598
47272  636022201 2026-03-25 11:02:42.577000+00:00      1615
27430  563162500 2026-03-25 11:02:42.672000+00:00      1607
19751  352927000 2026-03-25 11:02:42.719000+00:00      1602
25126  356758000 2026-03-25 11:02:42.781000+00:00      1611
9918   312716000 2026-03-25 11:02:43.155000+00:00      1617
30594  440021790 2026-03-25 11:02:43.171000+00:00      1601
27319  477476300 2026-03-25 11:02:43.467000+00:00      1611
12     416044000 2026-03-25 11:02:43.467000+00:00      1624
38412  636020892 2026-03-25 11:02:43.858000+00:00      1653
38711  563147100 2026-03-25 11:02:43.891000+00:00      1649
26619  219710000 2026-03-25 11:02:43.967000+00:00      1662
53039  636023189 2026-03-25 11:02:44.259000+00:00      1660
22218  353282000 2026-03-25 11:02:44.321000+00:00      1646
8391   440310510 2026-03-25 11:02:44.382000+00:00      1675
50928  440000340 2026-03-25 11:02:44.539000+00:00      1673
5263   636022201 2026-03-25 11:02:44.587000+00:00      1690
25275  352927000 2026-03-25 11:02:44.712000+00:00      1677
2177   356758000 2026-03-25 11:02:44.789000+00:00      1686
48638  538006103 2026-03-25 11:02:44.947000+00:00      1667
51029  477947700 2026-03-25 11:02:45.027000+00:00      1676
55802  312716000 2026-03-25 11:02:45.153000+00:00      1692
44894  352004507 2026-03-25 11:02:45.184000+00:00      1696
41878  477634100 2026-03-25 11:02:45.467000+00:00      1680
9446   416044000 2026-03-25 11:02:45.467000+00:00      1699
52772  352002591 2026-03-25 11:02:45.498000+00:00      1693
15632  636020892 2026-03-25 11:02:45.858000+00:00      1728
53392  563147100 2026-03-25 11:02:45.889000+00:00      1724
54022  219710000 2026-03-25 11:02:45.966000+00:00      1737
44636  563021700 2026-03-25 11:02:45.998000+00:00      1733
9170   636023189 2026-03-25 11:02:46.263000+00:00      1735
4324   440310510 2026-03-25 11:02:46.373000+00:00      1750
54606  440000340 2026-03-25 11:02:46.529000+00:00      1748
49598  538002641 2026-03-25 11:02:46.545000+00:00      1728
10726  636022201 2026-03-25 11:02:46.576000+00:00      1765
38151  352927000 2026-03-25 11:02:46.716000+00:00      1752
32860  356758000 2026-03-25 11:02:46.779000+00:00      1761
21667  312716000 2026-03-25 11:02:47.153000+00:00      1767
1169   311054300 2026-03-25 11:02:47.153000+00:00      1754
32103  273415260 2026-03-25 11:02:47.216000+00:00      1774
50687  219357000 2026-03-25 11:02:47.402000+00:00      1756
15805  636020552 2026-03-25 11:02:47.464000+00:00      1770
16214  416044000 2026-03-25 11:02:47.465000+00:00      1774
43212  563172200 2026-03-25 11:02:47.717000+00:00      1773
24859  636020892 2026-03-25 11:02:47.858000+00:00      1803
48118  563147100 2026-03-25 11:02:47.889000+00:00      1799
48533  219710000 2026-03-25 11:02:47.967000+00:00      1812
46733  636020590 2026-03-25 11:02:47.967000+00:00      1786
57782  636023189 2026-03-25 11:02:48.260000+00:00      1810
15259  440310510 2026-03-25 11:02:48.384000+00:00      1825
14378  440363000 2026-03-25 11:02:48.462000+00:00      1803
41278  511100779 2026-03-25 11:02:48.494000+00:00      1806
35714  440000340 2026-03-25 11:02:48.525000+00:00      1823
26821  636022201 2026-03-25 11:02:48.589000+00:00      1840
43740  563162500 2026-03-25 11:02:48.666000+00:00      1832
8941   352927000 2026-03-25 11:02:48.713000+00:00      1827
22127  356758000 2026-03-25 11:02:48.789000+00:00      1836
28658  312716000 2026-03-25 11:02:49.148000+00:00      1842
12715  416044000 2026-03-25 11:02:49.461000+00:00      1849
13720  477476300 2026-03-25 11:02:49.461000+00:00      1836
2914   636020892 2026-03-25 11:02:49.865000+00:00      1878
33232  563147100 2026-03-25 11:02:49.880000+00:00      1874
24717  219710000 2026-03-25 11:02:49.973000+00:00      1887
47545  636023189 2026-03-25 11:02:50.255000+00:00      1885
5214   353282000 2026-03-25 11:02:50.317000+00:00      1871
37478  440310510 2026-03-25 11:02:50.378000+00:00      1900
35343  440000340 2026-03-25 11:02:50.533000+00:00      1898
5258   636022201 2026-03-25 11:02:50.580000+00:00      1915
11595  352927000 2026-03-25 11:02:50.705000+00:00      1902
29388  356758000 2026-03-25 11:02:50.783000+00:00      1911
8050   538006103 2026-03-25 11:02:50.940000+00:00      1892
12604  312716000 2026-03-25 11:02:51.159000+00:00      1917
31734  352004507 2026-03-25 11:02:51.175000+00:00      1921
43498  416044000 2026-03-25 11:02:51.458000+00:00      1924
47479  352002591 2026-03-25 11:02:51.505000+00:00      1918
807    636020892 2026-03-25 11:02:51.865000+00:00      1953
12947  563147100 2026-03-25 11:02:51.881000+00:00      1949
36567  219710000 2026-03-25 11:02:51.975000+00:00      1962
41390  563021700 2026-03-25 11:02:51.991000+00:00      1958
14704  636023189 2026-03-25 11:02:52.256000+00:00      1960
11274  440310510 2026-03-25 11:02:52.380000+00:00      1975
51718  440000340 2026-03-25 11:02:52.536000+00:00      1973
36298  636022201 2026-03-25 11:02:52.581000+00:00      1990
36512  352927000 2026-03-25 11:02:52.707000+00:00      1977
11950  356758000 2026-03-25 11:02:52.786000+00:00      1986
52633  312716000 2026-03-25 11:02:53.144000+00:00      1992
38485  311054300 2026-03-25 11:02:53.144000+00:00      1979
949    440021790 2026-03-25 11:02:53.175000+00:00      1976
41031  273415260 2026-03-25 11:02:53.221000+00:00      1999
8402   219357000 2026-03-25 11:02:53.408000+00:00      1981
30968  416044000 2026-03-25 11:02:53.453000+00:00      1999
31247  636020552 2026-03-25 11:02:53.469000+00:00      1995
24468  636020892 2026-03-25 11:02:53.858000+00:00      2028

In [94]:
with pd.option_context("display.max_rows", None):
    display(df_sort[df_sort["mmsi"] == "414061000"])

Empty DataFrame
Columns: [mmsi, date_bucket, received_at, msg_type, sog, cog, nav_status, longitude, latitude, rssi, slot_num, snr]
Index: []

In [95]:
def get_NI(sog_raw):
    """SOG는 ×10 저장이므로 /10 후 NI 반환"""
    sog = sog_raw / 10.0
    if sog == 0:
        return None      # 정박/계류 → 별도 확인
    elif sog < 14:
        return 375       # 보고주기 10s → 2250/6
    elif sog < 23:
        return 225       # 보고주기  6s → 2250/10
    else:
        return 75        # 보고주기  2s → 2250/30

df_check = df_sort.copy()

# 선박별 이전 행의 slot_num, sog
df_check["prev_slot"] = df_check.groupby("mmsi")["slot_num"].shift(1)
df_check["prev_sog"]  = df_check.groupby("mmsi")["sog"].shift(1)

# 첫 번째 행(NaN) 제거
df_check = df_check.dropna(subset=["prev_slot", "prev_sog"]).copy()
df_check["prev_slot"] = df_check["prev_slot"].astype(int)

# NI 계산
df_check["NI"] = df_check["prev_sog"].apply(get_NI)

In [96]:
def slot_diff_wrap(prev, curr, max_slot=2250):
    diff = int(curr) - int(prev)
    if diff < 0:
        diff += max_slot   # 0으로 초기화된 경우 보정
    return diff

df_check["slot_diff"] = df_check.apply(
    lambda r: slot_diff_wrap(r["prev_slot"], r["slot_num"]), axis=1
)
df_check

,mmsi,date_bucket,received_at,msg_type,sog,cog,nav_status,longitude,latitude,rssi,slot_num,snr,prev_slot,prev_sog,NI,slot_diff
22520,636020892,2026-03-25 11:02:05.865000+00:00,2026-03-25 11:42:53.378000+00:00,3,264.0,301.0,15.0,129.41673,34.92316,-109.000000,228,11.400000,160,264.0,75,68
27626,356758000,2026-03-25 11:02:06.777000+00:00,2026-03-25 11:42:53.519000+00:00,3,297.0,990.0,3.0,128.74689,35.05979,-112.800003,261,6.400000,193,297.0,75,68
19793,636020892,2026-03-25 11:02:07.852000+00:00,2026-03-25 11:42:53.582000+00:00,3,264.0,301.0,3.0,129.41673,34.92316,-114.599998,303,4.600000,228,264.0,75,75
5007,440310510,2026-03-25 11:02:08.370000+00:00,2026-03-25 11:42:53.598000+00:00,3,259.0,2969.0,4.0,129.24993,35.09598,-100.699997,325,19.500000,257,259.0,75,68
56378,440000340,2026-03-25 11:02:08.523000+00:00,2026-03-25 11:42:53.613000+00:00,3,272.0,660.0,9.0,129.22618,34.94833,-103.300003,323,16.299999,255,272.0,75,68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12150,538006103,2026-03-25 11:21:38.938000+00:00,2026-03-25 11:45:25.485000+00:00,1,186.0,1914.0,15.0,129.18676,35.12498,-102.400002,1456,16.500000,1216,186.0,225,240
7352,312716000,2026-03-25 11:21:39.147000+00:00,2026-03-25 11:45:25.501000+00:00,1,234.0,2587.0,10.0,128.78993,35.06431,-105.400002,1463,14.900000,1389,234.0,75,74
29000,352004507,2026-03-25 11:21:39.174000+00:00,2026-03-25 11:45:25.518000+00:00,1,205.0,2472.0,12.0,129.35102,35.28782,-113.900002,1454,5.100000,1230,205.0,225,224
4355,416044000,2026-03-25 11:21:39.461000+00:00,2026-03-25 11:45:25.533000+00:00,1,266.0,1829.0,13.0,128.98792,34.89233,-108.599998,1474,10.900000,1399,266.0,75,75
19113,352002591,2026-03-25 11:21:39.493000+00:00,2026-03-25 11:45:25.548000+00:00,1,193.0,2725.0,2.0,129.20656,34.91304,-109.900002,1462,12.200000,1236,193.0,225,226

In [97]:
def is_slot_valid(row):
    NI = row["NI"]
    if NI is None:
        return None   # SOG=0은 별도 검토
    margin = 0.2 * NI
    diff   = row["slot_diff"]
    # slot_diff가 [0.8*NI, 1.2*NI] 범위 안에 있어야 정상
    return (NI - margin) <= diff <= (NI + margin)

df_check["slot_valid"] = df_check.apply(is_slot_valid, axis=1)
df_check

,mmsi,date_bucket,received_at,msg_type,sog,cog,nav_status,longitude,latitude,rssi,slot_num,snr,prev_slot,prev_sog,NI,slot_diff,slot_valid
22520,636020892,2026-03-25 11:02:05.865000+00:00,2026-03-25 11:42:53.378000+00:00,3,264.0,301.0,15.0,129.41673,34.92316,-109.000000,228,11.400000,160,264.0,75,68,True
27626,356758000,2026-03-25 11:02:06.777000+00:00,2026-03-25 11:42:53.519000+00:00,3,297.0,990.0,3.0,128.74689,35.05979,-112.800003,261,6.400000,193,297.0,75,68,True
19793,636020892,2026-03-25 11:02:07.852000+00:00,2026-03-25 11:42:53.582000+00:00,3,264.0,301.0,3.0,129.41673,34.92316,-114.599998,303,4.600000,228,264.0,75,75,True
5007,440310510,2026-03-25 11:02:08.370000+00:00,2026-03-25 11:42:53.598000+00:00,3,259.0,2969.0,4.0,129.24993,35.09598,-100.699997,325,19.500000,257,259.0,75,68,True
56378,440000340,2026-03-25 11:02:08.523000+00:00,2026-03-25 11:42:53.613000+00:00,3,272.0,660.0,9.0,129.22618,34.94833,-103.300003,323,16.299999,255,272.0,75,68,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12150,538006103,2026-03-25 11:21:38.938000+00:00,2026-03-25 11:45:25.485000+00:00,1,186.0,1914.0,15.0,129.18676,35.12498,-102.400002,1456,16.500000,1216,186.0,225,240,True
7352,312716000,2026-03-25 11:21:39.147000+00:00,2026-03-25 11:45:25.501000+00:00,1,234.0,2587.0,10.0,128.78993,35.06431,-105.400002,1463,14.900000,1389,234.0,75,74,True
29000,352004507,2026-03-25 11:21:39.174000+00:00,2026-03-25 11:45:25.518000+00:00,1,205.0,2472.0,12.0,129.35102,35.28782,-113.900002,1454,5.100000,1230,205.0,225,224,True
4355,416044000,2026-03-25 11:21:39.461000+00:00,2026-03-25 11:45:25.533000+00:00,1,266.0,1829.0,13.0,128.98792,34.89233,-108.599998,1474,10.900000,1399,266.0,75,75,True
19113,352002591,2026-03-25 11:21:39.493000+00:00,2026-03-25 11:45:25.548000+00:00,1,193.0,2725.0,2.0,129.20656,34.91304,-109.900002,1462,12.200000,1236,193.0,225,226,True

In [98]:
print("=== 전체 슬롯 검증 결과 ===")
print(df_check["slot_valid"].value_counts(dropna=False))

# 선박별 이상 비율
summary = df_check.groupby("mmsi")["slot_valid"].agg(
    total="count",
    valid=lambda x: x.sum(),
    invalid=lambda x: (x == False).sum(),
    sog_zero=lambda x: x.isna().sum(),
)
summary["invalid_rate(%)"] = (summary["invalid"] / summary["total"] * 100).round(2)
print("\n=== 선박별 요약 ===")
print(summary)

# 이상 행만 따로 확인
df_invalid = df_check[df_check["slot_valid"] == False]
print(f"\n이상 레코드 수: {len(df_invalid)}")
print(df_invalid[["mmsi", "date_bucket", "prev_slot", "slot_num", "slot_diff", "NI", "prev_sog"]])

=== 전체 슬롯 검증 결과 ===
slot_valid
True     9541
False      28
Name: count, dtype: int64

=== 선박별 요약 ===
           total  valid  invalid  sog_zero  invalid_rate(%)
mmsi
219357000    192    192        0         0             0.00
219710000    574    573        1         0             0.17
273415260    191    191        0         0             0.00
311054300    195    195        0         0             0.00
312716000    585    584        1         0             0.17
352002591    195    195        0         0             0.00
352004507    195    195        0         0             0.00
352927000    583    581        2         0             0.34
353282000    191    191        0         0             0.00
356758000    586    585        1         0             0.17
416044000    576    576        0         0             0.00
440000340    583    580        3         0             0.51
440021790    115    115        0         0             0.00
440310510    586    586        0         0             0.00
440363000    195    195        0         0             0.00
477476300    195    195        0         0             0.00
477634100    115    115        0         0             0.00
477947700    117    117        0         0             0.00
511100779    115    115        0         0             0.00
538002641    117    117        0         0             0.00
538006103    192    192        0         0             0.00
563021700    191    191        0         0             0.00
563147100    574    574        0         0             0.00
563162500    195    195        0         0             0.00
563172200    117    117        0         0             0.00
636020552    190    190        0         0             0.00
636020590    195    195        0         0             0.00
636020892    586    584        2         0             0.34
636022201    551    533       18         0             3.27
636023189    577    577        0         0             0.00

이상 레코드 수: 28
            mmsi                      date_bucket  prev_slot  slot_num  \
17843  636020892 2026-03-25 11:05:03.855000+00:00         78       137
42521  312716000 2026-03-25 11:11:19.161000+00:00        561       712
41664  219710000 2026-03-25 11:11:29.978000+00:00       1062      1120
8969   636022201 2026-03-25 11:11:30.583000+00:00       1090      1141
11443  636022201 2026-03-25 11:11:36.577000+00:00       1141      1373
22800  356758000 2026-03-25 11:11:36.780000+00:00       1229      1377
57896  636022201 2026-03-25 11:12:06.578000+00:00         18       248
46388  636022201 2026-03-25 11:12:16.577000+00:00        476       617
56877  636022201 2026-03-25 11:12:26.573000+00:00        850       993
15878  636022201 2026-03-25 11:12:36.576000+00:00       1141      1373
32813  636022201 2026-03-25 11:13:06.584000+00:00         18       248
16960  636022201 2026-03-25 11:13:16.586000+00:00        476       617
25815  636022201 2026-03-25 11:13:26.576000+00:00        850       993
1308   636022201 2026-03-25 11:13:36.586000+00:00       1141      1373
44924  636022201 2026-03-25 11:14:06.579000+00:00         18       248
19846  636022201 2026-03-25 11:14:16.588000+00:00        476       617
29970  440000340 2026-03-25 11:14:26.530000+00:00        838       988
47830  636022201 2026-03-25 11:14:26.578000+00:00        850       993
7715   636022201 2026-03-25 11:15:16.588000+00:00        476       617
46661  636020892 2026-03-25 11:17:37.864000+00:00       1262      1423
38704  352927000 2026-03-25 11:18:46.714000+00:00       1597      1746
55398  636022201 2026-03-25 11:19:16.576000+00:00        475       614
47808  636022201 2026-03-25 11:19:26.586000+00:00        839       997
1066   352927000 2026-03-25 11:19:46.706000+00:00       1597      1746
22762  440000340 2026-03-25 11:20:02.531000+00:00       2188        89
46881  636022201 2026-03-25 11:20:16.575000+00:00        475       614
31446  636022201 2026-03-25 11:20:26.587000+00:00        839       997
41391  440000340 2026-03-25 11:21:02.531000+00:00       2188        89

       slot_diff  NI  prev_sog
17843         59  75     264.0
42521        151  75     234.0
41664         58  75     297.0
8969          51  75     246.0
11443        232  75     246.0
22800        148  75     297.0
57896        230  75     246.0
46388        141  75     246.0
56877        143  75     246.0
15878        232  75     246.0
32813        230  75     246.0
16960        141  75     246.0
25815        143  75     246.0
1308         232  75     246.0
44924        230  75     246.0
19846        141  75     246.0
29970        150  75     272.0
47830        143  75     246.0
7715         141  75     246.0
46661        161  75     264.0
38704        149  75     268.0
55398        139  75     246.0
47808        158  75     246.0
1066         149  75     268.0
22762        151  75     272.0
46881        139  75     246.0
31446        158  75     246.0
41391        151  75     272.0

In [99]:
summary

           total  valid  invalid  sog_zero  invalid_rate(%)
mmsi
219357000    192    192        0         0             0.00
219710000    574    573        1         0             0.17
273415260    191    191        0         0             0.00
311054300    195    195        0         0             0.00
312716000    585    584        1         0             0.17
352002591    195    195        0         0             0.00
352004507    195    195        0         0             0.00
352927000    583    581        2         0             0.34
353282000    191    191        0         0             0.00
356758000    586    585        1         0             0.17
416044000    576    576        0         0             0.00
440000340    583    580        3         0             0.51
440021790    115    115        0         0             0.00
440310510    586    586        0         0             0.00
440363000    195    195        0         0             0.00
477476300    195    195        0         0             0.00
477634100    115    115        0         0             0.00
477947700    117    117        0         0             0.00
511100779    115    115        0         0             0.00
538002641    117    117        0         0             0.00
538006103    192    192        0         0             0.00
563021700    191    191        0         0             0.00
563147100    574    574        0         0             0.00
563162500    195    195        0         0             0.00
563172200    117    117        0         0             0.00
636020552    190    190        0         0             0.00
636020590    195    195        0         0             0.00
636020892    586    584        2         0             0.34
636022201    551    533       18         0             3.27
636023189    577    577        0         0             0.00

In [100]:
with pd.option_context("display.max_rows", None):
    display(df_check[(df_check["mmsi"] == "414061000")&(df_check["slot_valid"] == False)][["date_bucket","slot_num","slot_diff","slot_valid"]])

Empty DataFrame
Columns: [date_bucket, slot_num, slot_diff, slot_valid]
Index: []

In [101]:
cols = ["date_bucket", "slot_num", "slot_diff", "slot_valid"]

# 해당 선박만 추출 후 위치 인덱스 리셋
df_ship = df_check[df_check["mmsi"] == "273841100"].reset_index(drop=True)

# False인 행의 위치(position) 추출
false_pos = df_ship[df_ship["slot_valid"] == False].index.tolist()

# 앞뒤 n행씩 위치 확장
n = 2
expanded_pos = set()
for pos in false_pos:
    for i in range(max(0, pos - n), min(len(df_ship), pos + n + 1)):
        expanded_pos.add(i)

expanded_pos = sorted(expanded_pos)

# 강조 출력
def highlight_false(row):
    if row["slot_valid"] == False:
        return ["background-color: #ffcccc"] * len(row)
    return [""] * len(row)

with pd.option_context("display.max_rows", None):
    display(
        df_ship.loc[expanded_pos, cols]
        .style.apply(highlight_false, axis=1)
    )

In [102]:
cols = ["date_bucket", "slot_num", "slot_diff", "slot_valid"]
def highlight_false(row):
  if row["slot_valid"] == False:
      return ["background-color: #ffcccc"] * len(row)
  return [""] * len(row)
n = 2  # 앞뒤 행 수
for mmsi in sorted(df_check["mmsi"].unique()):
  df_ship = df_check[df_check["mmsi"] == mmsi].reset_index(drop=True)
  # False인 행이 없으면 스킵
  false_pos = df_ship[df_ship["slot_valid"] == False].index.tolist()
  if not false_pos:
      continue
  print(f"\n{'='*60}")
  print(f"MMSI: {mmsi}  |  이상 건수: {len(false_pos)}건")
  print(f"{'='*60}")
  # 앞뒤 n행씩 확장
  expanded_pos = set()
  for pos in false_pos:
      for i in range(max(0, pos - n), min(len(df_ship), pos + n + 1)):
          expanded_pos.add(i)
  expanded_pos = sorted(expanded_pos)
  with pd.option_context("display.max_rows", None):
      display(
          df_ship.loc[expanded_pos, cols]
          .style.apply(highlight_false, axis=1)
      )

============================================================
MMSI: 219710000  |  이상 건수: 1건
============================================================

============================================================
MMSI: 312716000  |  이상 건수: 1건
============================================================

============================================================
MMSI: 352927000  |  이상 건수: 2건
============================================================

============================================================
MMSI: 356758000  |  이상 건수: 1건
============================================================

============================================================
MMSI: 440000340  |  이상 건수: 3건
============================================================

============================================================
MMSI: 636020892  |  이상 건수: 2건
============================================================

============================================================
MMSI: 636022201  |  이상 건수: 18건
============================================================